### ISSUE TITLE
Finding out if monsters cannot spawn

### ISSUE THREAD

**Issue by kangarko** [Angeschossen/LandsAPI#3]
I've received a user ticket to connect to Lands to check if monsters spawning is disabled

![a](https://i.imgur.com/lhI3vZt.png)

Is this the right way to do it? If the method below returns false then I can prevent my custom monster from spawning?

![a](https://i.imgur.com/nADvYWM.png)

**Comment by Angeschossen** [comment]
Dear,

I'm sorry for the late reply. I missed your message.
In general you only need the LandsArea.

However, I would recommend doing it like this, since admins can also disable monster spawn in the wilderness with /lands admin wilderness.

`    private static final LandsIntegration landsIntegration;

    public static boolean hasMonsterSpawn(Location location) {
        LandWorld world = landsIntegration.getLandWorld(location.getWorld());
        if (world == null) {
            return true;
        }

        return world.hasLandSetting(location, LandSetting.MONSTER_SPAWN);
    }`
